# web port
server:
  port: 7078
# no web
#spring:
#  main:
#    web-environment: false

# log config
#logging:
#  config: classpath:logback.xml

### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"  调度器地址
xxl:
  job:
    admin:
#      addresses: http://10.181.22.194:8088/admin
      addresses: http://10.254.244.161:7001/pro-platform/admin
    ### xxl-job, access token
    accessToken:
    ### xxl-job executor appname 执行器名称
    executor:
      appname: htht-job-executor-download
      address:
      ip: #10.181.22.247
      port: 9998
      logpath: /home/htht/data/HTHT/log/download
      logretentiondays: 30

mybatis-plus:
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:/mapper/**/*.xml,/mapper/*.xml
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    # mybatis缓存配置
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    database-id: mysql
  global-config:
    db-config:
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      id-type: assign_uuid
spring:
  profiles:
    active: pro
