### web
spring.main.allow-bean-definition-overriding=true
#### actuator
#management.server.servlet.context-path=/actuator
#management.health.mail.enabled=false

### xxl-job, email
spring.mail.host=smtp.qq.com
spring.mail.port=25
spring.mail.username=xxx@qq.com
spring.mail.from=xxx@qq.com
spring.mail.password=xxx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory

### xxl-job, access token
xxl.job.accessToken=

### xxl-job, i18n (default is zh_CN, and you can choose "zh_CN", "zh_TC" and "en")
xxl.job.i18n=zh_CN

## xxl-job, triggerpool max size
xxl.job.triggerpool.fast.max=200
xxl.job.triggerpool.slow.max=100

### xxl-job, log retention days
xxl.job.logretentiondays=30


token.expiration.Time=1800

token.authPath.exclude=/v2-docs,/swagger-resources,/swagger-resources/configuration/ui,/doc.html\
  ,/lot/log/**,/lot/onOff/set,/system/user/getCurrentUser,/system-service/res/**\
  ,/random/image,/heartbeat,/**/swagger-ui.html,/webjars/**,/v2/**,/swagger-resources/**,/system/orgs/export,/favicon.ico,\
  /webHook/test,/common/downloadExcel,/webjars/**,/error,/v2/api-docs,/api/**,/registry/list,/logReport/list

swagger.enabled=false


eureka.client.serviceUrl.defaultZone=http://127.0.0.1:7001/eureka
#eureka.client.serviceUrl.defaultZone=http://10.181.22.194:7001/eureka
feign.hystrix.enabled=false
ribbon.eureka.enabled=true

xssParam.splitChar: @
xssParam.filterChar: >@<@\'@\"@\\@#@(@)
xssParam.replaceChar: \uFF1E\u2019@\uFF1C@\u2018@\u201C@\uFF3C@\uFF03@\uFF08@\uFF09
