eureka.client.serviceUrl.defaultZone=http://10.181.22.194:7001/eureka
#eureka.client.serviceUrl.defaultZone=http://127.0.0.1:7001/eureka
feign.hystrix.enabled=false
ribbon.eureka.enabled=true

token.expiration.Time=1800

token.authPath.exclude=/v2-docs,/swagger-resources,/swagger-resources/configuration/ui,/doc.html\
  ,/lot/log/**,/lot/onOff/set,/system/user/getCurrentUser,/system-service/res/**\
  ,/random/image,/heartbeat,/**/swagger-ui.html,/webjars/**,/v2/**,/swagger-resources/**,/system/orgs/export,/favicon.ico,\
  /webHook/test,/common/downloadExcel,/webjars/**,/error,/index/info,/feedback/management/list,/notice/info/list,\
  /feedback/management/replyList,/region/info/getWkt,/dic/identifyList

log.path.exclude=/system-service/res/**,/report/download/**

#统一平台的后台 与 与单个公用一套，这里是标识
chooseUnitPaltForm=true

ribbon.ReadTimeout=60000
ribbon.ConnectTimeout=60000
ribbon.eager-load.enabled=true

xssParam.splitChar: @
xssParam.filterChar: >@<@\'@\"@\\@#@(@)
xssParam.replaceChar: \uFF1E\u2019@\uFF1C@\u2018@\u201C@\uFF3C@\uFF03@\uFF08@\uFF09
